[package]
name = "map_tests"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstutil = { path = "../abstutil" }
convert_osm = { path = "../convert_osm" }
map_model = { path = "../map_model" }
