[package]
name = "parking_mapper"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[features]
default = ["map_gui/native", "reqwest", "widgetry/native-backend"]

[dependencies]
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
anyhow = "1.0.38"
fs-err = "2.6.0"
geom = { path = "../geom" }
log = "0.4.14"
map_gui = { path = "../map_gui" }
map_model = { path = "../map_model" }
reqwest = { version = "0.11.0", optional = true, default-features=false, features=["blocking", "rustls-tls"] }
structopt = "0.3.23"
widgetry = { path = "../widgetry" }
xmltree = "0.10.1"
