[package]
name = "traffic_signal_data"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
include_dir = { git = "https://github.com/dabreegster/include_dir", branch = "union" }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.61"
