[package]
name = "osm_viewer"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["map_gui/native", "widgetry/native-backend"]
wasm = ["getrandom/js", "map_gui/wasm", "wasm-bindgen", "widgetry/wasm-backend"]

[dependencies]
abstio = { path = "../../abstio" }
abstutil = { path = "../../abstutil" }
geom = { path = "../../geom" }
getrandom = { workspace = true, optional = true }
map_gui = { path = "../../map_gui" }
map_model = { path = "../../map_model" }
structopt = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
widgetry = { path = "../../widgetry" }
